import{describe,expect,it}from"vitest";import{createInitialState,type FighterInput}from"@forged-fighter/core";import{advanceAttack,startBounceLauncher}from"./runtime.js";import{BOUNCE_LAUNCHER}from"./moves.js";import{EMPTY_COMBO}from"./combo.js";import{DEFAULT_JUGGLE_LIMIT}from"./air-combat.js";import{resolveBounceLauncherContact}from"./bounce-launcher-resolution.js";
const n=():FighterInput=>({left:false,right:false,up:false,down:false,light:false,medium:false,heavy:false,special:false,throw:false});
const active=()=>{let a={...createInitialState().fighters[0],x:0};a=startBounceLauncher(a,{...n(),special:true});for(let i=0;i<BOUNCE_LAUNCHER.startup;i++)a=advanceAttack(a);return a;};const none={wall:false,ground:false};
describe("bounce launcher resolution",()=>{
 it("consumes two juggle points and grants bounce entitlement on hit",()=>{const d={...createInitialState().fighters[1],x:60};const r=resolveBounceLauncherContact(active(),d,n(),{points:0,hits:0},EMPTY_COMBO,none,12);expect(r.didDamage).toBe(true);expect(r.juggle).toEqual({points:2,hits:1});expect(r.combo.hits).toBe(1);expect(r.entitlement).toEqual({wall:true,ground:true});});
 it("does not grant entitlement when blocked",()=>{const d={...createInitialState().fighters[1],x:60,facing:-1 as const};const r=resolveBounceLauncherContact(active(),d,{...n(),right:true},{points:0,hits:0},EMPTY_COMBO,none,12);expect(r.didDamage).toBe(false);expect(r.juggle).toEqual({points:0,hits:0});expect(r.entitlement).toEqual(none);});
 it("does not change accounting on miss",()=>{const d={...createInitialState().fighters[1],x:500};const r=resolveBounceLauncherContact(active(),d,n(),{points:0,hits:0},EMPTY_COMBO,none,12);expect(r.didDamage).toBe(false);expect(r.combo).toEqual(EMPTY_COMBO);expect(r.entitlement).toEqual(none);});
 it("does not resolve with insufficient juggle budget",()=>{const a=active(),d={...createInitialState().fighters[1],x:60},j={points:DEFAULT_JUGGLE_LIMIT-1,hits:2};const r=resolveBounceLauncherContact(a,d,n(),j,EMPTY_COMBO,none,12);expect(r.didDamage).toBe(false);expect(r.attacker).toEqual(a);expect(r.defender).toEqual(d);expect(r.juggle).toEqual(j);});
});
