import{describe,expect,it}from"vitest";import{createInitialState,type FighterInput}from"@forged-fighter/core";import{beginThrow}from"./throws.js";import{prepareCombatInputs}from"./input-preparation.js";
const n=():FighterInput=>({left:false,right:false,up:false,down:false,light:false,medium:false,heavy:false,special:false,throw:false});
describe("combat input preparation",()=>{
 it("ticks hitstop before simulation",()=>{const s=createInitialState(),state={...s,fighters:[{...s.fighters[0],hitstopFrames:2},s.fighters[1]]as const};const r=prepareCombatInputs(state,[n(),n()],[null,null]);expect(r.simState.fighters[0].hitstopFrames).toBe(1);});
 it("throw lock freezes velocity and neutralizes action movement/buttons",()=>{const s=createInitialState(),state={...s,fighters:[{...s.fighters[0],vx:9,vy:4},s.fighters[1]]as const},i={...n(),right:true,light:true};const r=prepareCombatInputs(state,[i,n()],[beginThrow(),null]);expect(r.simState.fighters[0].vx).toBe(0);expect(r.simState.fighters[0].vy).toBe(0);expect(r.actionInputs[0].right).toBe(false);expect(r.actionInputs[0].light).toBe(false);});
 it("holding back under nearby attack guards without walking",()=>{const s=createInitialState(),a={...s.fighters[0],x:0,facing:1 as const},b={...s.fighters[1],x:100,mode:"attack" as const};const r=prepareCombatInputs({...s,fighters:[a,b]},[{...n(),left:true},n()],[null,null]);expect(r.lockedInputs[0].left).toBe(true);expect(r.movement[0].left).toBe(false);});
 it("holding back outside threat range still moves",()=>{const s=createInitialState(),a={...s.fighters[0],x:0,facing:1 as const},b={...s.fighters[1],x:300,mode:"attack" as const};const r=prepareCombatInputs({...s,fighters:[a,b]},[{...n(),left:true},n()],[null,null]);expect(r.movement[0].left).toBe(true);});
 it("preserves command ownership independently from movement filtering",()=>{const s=createInitialState();const r=prepareCombatInputs(s,[{...n(),down:true,medium:true,special:true},n()],[null,null]);expect(r.commands[0].owner).toBe("super");});
});
