import{DEFAULT_BOUNCE_RULES,resolveGroundBounce,resolveWallBounce}from"./bounce.js";import{stepMatch,tickHitstop,tickStun,type FighterInput,type FighterState,type MatchState}from"@forged-fighter/core";import{advanceAttack,jumpCancelLauncher,resolveAirJuggleLight,resolveBasicSuper,resolveBounceLauncher,resolveHeavyLauncher,resolveJuggleLight,resolveStandingLight,startAirJuggleLight,startBounceLauncher,startHeavyLauncher,startLight,tryStartSuper}from"./runtime.js";import{addComboHit,resetComboIfExpired,scaledDamage}from"./combo.js";import{asCombatMatchState,type CombatMatchState}from"./combat-match.js";import{AIR_JUGGLE_LIGHT,BASIC_SUPER,BOUNCE_LAUNCHER,JUGGLE_LIGHT,STANDING_HEAVY_LAUNCHER,STANDING_LIGHT}from"./moves.js";import{applyJuggle,canJuggle}from"./air-combat.js";import{advanceThrow,BASIC_THROW,beginThrow,canTechThrow,canThrowConnect,isThrowLocked}from"./throws.js";import{resolveThrowAttempt}from"./throw-resolution.js";import{resolveSuperContact}from"./super-resolution.js";import{resolveAirJuggleLightContact}from"./air-juggle-resolution.js";import{resolveBounceLauncherContact}from"./bounce-launcher-resolution.js";import{resolveHeavyLauncherContact}from"./heavy-launcher-resolution.js";import{absorbArmorHit,armorDamage,hasArmor,isCounterHitTarget,resolveParry,tickDefenseReaction}from"./defense-reactions.js";import{gainMeter,LIGHT_HIT_METER_GAIN}from"./meter.js";import{resolveProjectileContacts,spawnBasicProjectile,tickProjectiles}from"./projectiles.js";import{resolveCombatCommand}from"./command-resolver.js";import{resolveMeleeStarter}from"./move-execution.js";
function guardInput(input:FighterInput,facing:-1|1):FighterInput{return{...input,left:facing===1?input.left:false,right:facing===-1?input.right:false};}
function holdsBack(input:FighterInput,facing:-1|1):boolean{return facing===1?input.left:input.right;}
function movementInput(input:FighterInput,f:FighterState,opponent:FighterState):FighterInput{const threatening=opponent.mode==="attack"&&Math.abs(opponent.x-f.x)<=140;return threatening&&holdsBack(input,f.facing)?{...input,left:false,right:false}:input;}
export function stepCombatMatch(state:MatchState,inputs:readonly[FighterInput,FighterInput]):CombatMatchState{
 const combat=asCombatMatchState(state),frame=state.frame;let projectiles=[...combat.projectiles],nextProjectileId=combat.nextProjectileId;
 let combos=[resetComboIfExpired(combat.combos[0],frame),resetComboIfExpired(combat.combos[1],frame)] as const;let bounceEntitlements=[{...combat.bounceEntitlements[0]},{...combat.bounceEntitlements[1]}] as [typeof combat.bounceEntitlements[0],typeof combat.bounceEntitlements[1]];let juggles=[combat.juggles[0],combat.juggles[1]] as [typeof combat.juggles[0],typeof combat.juggles[1]];let throws=[combat.throws[0],combat.throws[1]] as [typeof combat.throws[0],typeof combat.throws[1]];let defenseReactions=[{...combat.defenseReactions[0]},{...combat.defenseReactions[1]}] as [typeof combat.defenseReactions[0],typeof combat.defenseReactions[1]];
 const guards=inputs;
 const frozen=state.fighters.map(f=>f.hitstopFrames>0?tickHitstop(f):f) as [FighterState,FighterState];
 const throwLockedFighters=frozen.map((fighter,index)=>isThrowLocked(throws[index as 0|1])?{...fighter,vx:0,vy:0}:fighter) as [FighterState,FighterState];
 const simState={...state,fighters:throwLockedFighters as readonly[FighterState,FighterState]};
 const resolvedCommands=[resolveCombatCommand(inputs[0],isThrowLocked(throws[0])),resolveCombatCommand(inputs[1],isThrowLocked(throws[1]))] as const;
 const lockedInputs=[resolvedCommands[0].lockedInput,resolvedCommands[1].lockedInput] as const,projectileCommands=[resolvedCommands[0].owner==="projectile",resolvedCommands[1].owner==="projectile"] as const;for(const player of [0,1] as const){if(projectileCommands[player]&&!combat.projectileCommandHeld[player]&&combat.fighters[player].mode==="idle"){const[p,next]=spawnBasicProjectile(nextProjectileId,combat.fighters[player]);projectiles.push(p);nextProjectileId=next;}}
 const commandA=resolvedCommands[0].owner==="super",commandB=resolvedCommands[1].owner==="super";
 const actionInputA=resolvedCommands[0].actionInput,actionInputB=resolvedCommands[1].actionInput;const movement=[movementInput(actionInputA,simState.fighters[0],simState.fighters[1]),movementInput(actionInputB,simState.fighters[1],simState.fighters[0])] as const;
 let base=stepMatch(simState,movement);const landedA=simState.fighters[0].mode==="air-hitstun"&&base.fighters[0].mode==="knockdown",landedB=simState.fighters[1].mode==="air-hitstun"&&base.fighters[1].mode==="knockdown";let a=tryStartSuper(base.fighters[0],lockedInputs[0]),b=tryStartSuper(base.fighters[1],lockedInputs[1]);if(!commandA)a=resolveMeleeStarter(a,actionInputA);if(!commandB)b=resolveMeleeStarter(b,actionInputB);
 if(resolvedCommands[0].owner==="throw"&&!throws[0]&&a.mode==="idle")throws[0]=beginThrow();if(resolvedCommands[1].owner==="throw"&&!throws[1]&&b.mode==="idle")throws[1]=beginThrow();
 {const r=resolveThrowAttempt(a,b,throws[0],throws[1],inputs[1].throw);a=r.attacker;b=r.defender;throws[0]=r.attempt;}
 {const r=resolveThrowAttempt(b,a,throws[1],throws[0],inputs[0].throw);b=r.attacker;a=r.defender;throws[1]=r.attempt;}
 a=jumpCancelLauncher(a,actionInputA);b=jumpCancelLauncher(b,actionInputB);
 {const r=resolveSuperContact(a,b,guards[1]);a=r.attacker;b=r.defender;if(r.didDamage)combos=[addComboHit(combos[0],BASIC_SUPER.damage,frame).combo,combos[1]];}{const r=resolveSuperContact(b,a,guards[0]);b=r.attacker;a=r.defender;if(r.didDamage)combos=[combos[0],addComboHit(combos[1],BASIC_SUPER.damage,frame).combo];}
 {const r=resolveAirJuggleLightContact(a,b,juggles[0],combos[0],frame);a=r.attacker;b=r.defender;juggles[0]=r.juggle;combos=[r.combo,combos[1]];}
 {const r=resolveAirJuggleLightContact(b,a,juggles[1],combos[1],frame);b=r.attacker;a=r.defender;juggles[1]=r.juggle;combos=[combos[0],r.combo];}
 {const r=resolveBounceLauncherContact(a,b,guards[1],juggles[0],combos[0],bounceEntitlements[1],frame);a=r.attacker;b=r.defender;juggles[0]=r.juggle;combos=[r.combo,combos[1]];bounceEntitlements[1]=r.entitlement;}
 {const r=resolveBounceLauncherContact(b,a,guards[0],juggles[1],combos[1],bounceEntitlements[0],frame);b=r.attacker;a=r.defender;juggles[1]=r.juggle;combos=[combos[0],r.combo];bounceEntitlements[0]=r.entitlement;}
 {const r=resolveHeavyLauncherContact(a,b,guards[1],juggles[0],combos[0],defenseReactions[1],frame);a=r.attacker;b=r.defender;juggles[0]=r.juggle;combos=[r.combo,combos[1]];defenseReactions[1]=r.defenseReaction;}
 {const r=resolveHeavyLauncherContact(b,a,guards[0],juggles[1],combos[1],defenseReactions[0],frame);b=r.attacker;a=r.defender;juggles[1]=r.juggle;combos=[combos[0],r.combo];defenseReactions[0]=r.defenseReaction;}
 let bounces=[{...combat.bounces[0]},{...combat.bounces[1]}] as [typeof combat.bounces[0],typeof combat.bounces[1]];const ga=bounces[0].groundBounces,gb=bounces[1].groundBounces;if(bounceEntitlements[0].ground&&canJuggle(juggles[1],DEFAULT_BOUNCE_RULES.groundJuggleCost))[a,bounces[0]]=resolveGroundBounce(combat.fighters[0],a,bounces[0]);if(bounces[0].groundBounces>ga){juggles[1]=applyJuggle(juggles[1],DEFAULT_BOUNCE_RULES.groundJuggleCost);bounceEntitlements[0]={...bounceEntitlements[0],ground:false};}if(bounceEntitlements[1].ground&&canJuggle(juggles[0],DEFAULT_BOUNCE_RULES.groundJuggleCost))[b,bounces[1]]=resolveGroundBounce(combat.fighters[1],b,bounces[1]);if(bounces[1].groundBounces>gb){juggles[0]=applyJuggle(juggles[0],DEFAULT_BOUNCE_RULES.groundJuggleCost);bounceEntitlements[1]={...bounceEntitlements[1],ground:false};}const wa=bounces[0].wallBounces,wb=bounces[1].wallBounces;if(bounceEntitlements[0].wall&&canJuggle(juggles[1],DEFAULT_BOUNCE_RULES.wallJuggleCost))[a,bounces[0]]=resolveWallBounce(a,bounces[0]);if(bounces[0].wallBounces>wa){juggles[1]=applyJuggle(juggles[1],DEFAULT_BOUNCE_RULES.wallJuggleCost);bounceEntitlements[0]={...bounceEntitlements[0],wall:false};}if(bounceEntitlements[1].wall&&canJuggle(juggles[0],DEFAULT_BOUNCE_RULES.wallJuggleCost))[b,bounces[1]]=resolveWallBounce(b,bounces[1]);if(bounces[1].wallBounces>wb){juggles[0]=applyJuggle(juggles[0],DEFAULT_BOUNCE_RULES.wallJuggleCost);bounceEntitlements[1]={...bounceEntitlements[1],wall:false};}
 const juggleHpB=b.health;if(canJuggle(juggles[0],1)){[a,b]=resolveJuggleLight(a,b,scaledDamage(JUGGLE_LIGHT.damage,combos[0].hits));if(b.health<juggleHpB){juggles[0]=applyJuggle(juggles[0],1);combos=[addComboHit(combos[0],JUGGLE_LIGHT.damage,frame).combo,combos[1]];}}
 const juggleHpA=a.health;if(canJuggle(juggles[1],1)){[b,a]=resolveJuggleLight(b,a,scaledDamage(JUGGLE_LIGHT.damage,combos[1].hits));if(a.health<juggleHpA){juggles[1]=applyJuggle(juggles[1],1);combos=[combos[0],addComboHit(combos[1],JUGGLE_LIGHT.damage,frame).combo];}}
 const hpB=b.health,armorB=hasArmor(defenseReactions[1]),parryB=defenseReactions[1].kind==="parry",counterB=isCounterHitTarget(b.mode);[a,b]=resolveStandingLight(a,b,guards[1],armorDamage(defenseReactions[1],scaledDamage(STANDING_LIGHT.damage,combos[0].hits)));if(parryB&&a.attack?.contact==="hit"){defenseReactions[1]=resolveParry(defenseReactions[1]);a={...a,attack:a.attack?{...a.attack,contact:"parry"}:a.attack};b={...combat.fighters[1],hitstopFrames:b.hitstopFrames};}else if(armorB&&a.attack?.contact==="hit"){defenseReactions[1]=absorbArmorHit(defenseReactions[1]);b={...b,mode:"idle",stunFrames:0};}else if(b.health<hpB){if(counterB&&a.attack?.contact==="hit")a={...a,attack:{...a.attack,contact:"counter"}};a=gainMeter(a,LIGHT_HIT_METER_GAIN);combos=[addComboHit(combos[0],STANDING_LIGHT.damage,frame).combo,combos[1]];}
 const hpA=a.health,armorA=hasArmor(defenseReactions[0]),parryA=defenseReactions[0].kind==="parry",counterA=isCounterHitTarget(a.mode);[b,a]=resolveStandingLight(b,a,guards[0],armorDamage(defenseReactions[0],scaledDamage(STANDING_LIGHT.damage,combos[1].hits)));if(parryA&&b.attack?.contact==="hit"){defenseReactions[0]=resolveParry(defenseReactions[0]);b={...b,attack:b.attack?{...b.attack,contact:"parry"}:b.attack};a={...combat.fighters[0],hitstopFrames:a.hitstopFrames};}else if(armorA&&b.attack?.contact==="hit"){defenseReactions[0]=absorbArmorHit(defenseReactions[0]);a={...a,mode:"idle",stunFrames:0};}else if(a.health<hpA){if(counterA&&b.attack?.contact==="hit")b={...b,attack:{...b.attack,contact:"counter"}};b=gainMeter(b,LIGHT_HIT_METER_GAIN);combos=[combos[0],addComboHit(combos[1],STANDING_LIGHT.damage,frame).combo];}
 const preStunA=a.mode,preStunB=b.mode;if(!landedA&&a.hitstopFrames===0&&(a.mode==="hitstun"||a.mode==="air-hitstun"||a.mode==="knockdown"||a.mode==="blockstun"))a=tickStun(a);if(!landedB&&b.hitstopFrames===0&&(b.mode==="hitstun"||b.mode==="air-hitstun"||b.mode==="knockdown"||b.mode==="blockstun"))b=tickStun(b);const recoveredA=(preStunA==="hitstun"||preStunA==="knockdown")&&a.mode==="idle";const recoveredB=(preStunB==="hitstun"||preStunB==="knockdown")&&b.mode==="idle";if(recoveredA){juggles[1]={points:0,hits:0};bounces[0]={wallBounces:0,groundBounces:0};bounceEntitlements[0]={wall:false,ground:false};}if(recoveredB){juggles[0]={points:0,hits:0};bounces[1]={wallBounces:0,groundBounces:0};bounceEntitlements[1]={wall:false,ground:false};}
 a=advanceAttack(a);b=advanceAttack(b);defenseReactions=[tickDefenseReaction(defenseReactions[0]),tickDefenseReaction(defenseReactions[1])];
 const projectileContact=resolveProjectileContacts(tickProjectiles(projectiles),[a,b]);[a,b]=projectileContact.fighters;
 return{...base,fighters:[a,b] as readonly[FighterState,FighterState],combos,throws,juggles,bounces,bounceEntitlements,defenseReactions,projectiles:projectileContact.projectiles,nextProjectileId,projectileCommandHeld:projectileCommands};
}
