import{DEFAULT_BOUNCE_RULES,resolveGroundBounce,resolveWallBounce}from"./bounce.js";import{stepMatch,tickHitstop,tickStun,type FighterInput,type FighterState,type MatchState}from"@forged-fighter/core";import{advanceAttack,jumpCancelLauncher,resolveAirJuggleLight,resolveBasicSuper,resolveBounceLauncher,resolveHeavyLauncher,resolveJuggleLight,resolveStandingLight,startAirJuggleLight,startBounceLauncher,startHeavyLauncher,startLight,tryStartSuper}from"./runtime.js";import{addComboHit,resetComboIfExpired,scaledDamage}from"./combo.js";import{asCombatMatchState,type CombatMatchState}from"./combat-match.js";import{AIR_JUGGLE_LIGHT,BASIC_SUPER,BOUNCE_LAUNCHER,JUGGLE_LIGHT,STANDING_HEAVY_LAUNCHER,STANDING_LIGHT}from"./moves.js";import{applyJuggle,canJuggle}from"./air-combat.js";import{advanceThrow,BASIC_THROW,beginThrow,canTechThrow,canThrowConnect,isThrowLocked}from"./throws.js";import{absorbArmorHit,armorDamage,hasArmor,isCounterHitTarget,resolveParry,tickDefenseReaction}from"./defense-reactions.js";import{gainMeter,LIGHT_HIT_METER_GAIN}from"./meter.js";import{resolveProjectileContacts,spawnBasicProjectile,tickProjectiles}from"./projectiles.js";
function guardInput(input:FighterInput,facing:-1|1):FighterInput{return{...input,left:facing===1?input.left:false,right:facing===-1?input.right:false};}
function holdsBack(input:FighterInput,facing:-1|1):boolean{return facing===1?input.left:input.right;}
function movementInput(input:FighterInput,f:FighterState,opponent:FighterState):FighterInput{const threatening=opponent.mode==="attack"&&Math.abs(opponent.x-f.x)<=140;return threatening&&holdsBack(input,f.facing)?{...input,left:false,right:false}:input;}
export function stepCombatMatch(state:MatchState,inputs:readonly[FighterInput,FighterInput]):CombatMatchState{
 const combat=asCombatMatchState(state),frame=state.frame;let projectiles=[...combat.projectiles],nextProjectileId=combat.nextProjectileId;const superSignatures=[inputs[0].down&&inputs[0].special,inputs[1].down&&inputs[1].special] as const;const projectileCommands=[inputs[0].medium&&inputs[0].special&&!superSignatures[0],inputs[1].medium&&inputs[1].special&&!superSignatures[1]] as const;
 let combos=[resetComboIfExpired(combat.combos[0],frame),resetComboIfExpired(combat.combos[1],frame)] as const;let bounceEntitlements=[{...combat.bounceEntitlements[0]},{...combat.bounceEntitlements[1]}] as [typeof combat.bounceEntitlements[0],typeof combat.bounceEntitlements[1]];let juggles=[combat.juggles[0],combat.juggles[1]] as [typeof combat.juggles[0],typeof combat.juggles[1]];let throws=[combat.throws[0],combat.throws[1]] as [typeof combat.throws[0],typeof combat.throws[1]];let defenseReactions=[{...combat.defenseReactions[0]},{...combat.defenseReactions[1]}] as [typeof combat.defenseReactions[0],typeof combat.defenseReactions[1]];
 const guards=inputs;for(const player of [0,1] as const){if(projectileCommands[player]&&!combat.projectileCommandHeld[player]&&combat.fighters[player].mode==="idle"){const[p,next]=spawnBasicProjectile(nextProjectileId,combat.fighters[player]);projectiles.push(p);nextProjectileId=next;}}
 const frozen=state.fighters.map(f=>f.hitstopFrames>0?tickHitstop(f):f) as [FighterState,FighterState];
 const throwLockedFighters=frozen.map((fighter,index)=>isThrowLocked(throws[index as 0|1])?{...fighter,vx:0,vy:0}:fighter) as [FighterState,FighterState];
 const simState={...state,fighters:throwLockedFighters as readonly[FighterState,FighterState]};
 const neutralize=(input:FighterInput):FighterInput=>({...input,left:false,right:false,up:false,down:false,light:false,medium:false,heavy:false,special:false});
 const lockedInputs=[isThrowLocked(throws[0])?neutralize(inputs[0]):inputs[0],isThrowLocked(throws[1])?neutralize(inputs[1]):inputs[1]] as const;
 const commandA=lockedInputs[0].down&&lockedInputs[0].special,commandB=lockedInputs[1].down&&lockedInputs[1].special;const commandSafe=(input:FighterInput,superCommand:boolean,projectileCommand:boolean):FighterInput=>projectileCommand?{...input,medium:false,special:false,throw:false}:superCommand?{...input,down:false,throw:false}:input;
 const actionInputA=commandSafe(lockedInputs[0],commandA,projectileCommands[0]),actionInputB=commandSafe(lockedInputs[1],commandB,projectileCommands[1]);const movement=[movementInput(actionInputA,simState.fighters[0],simState.fighters[1]),movementInput(actionInputB,simState.fighters[1],simState.fighters[0])] as const;
 let base=stepMatch(simState,movement);const landedA=simState.fighters[0].mode==="air-hitstun"&&base.fighters[0].mode==="knockdown",landedB=simState.fighters[1].mode==="air-hitstun"&&base.fighters[1].mode==="knockdown";let a=tryStartSuper(base.fighters[0],lockedInputs[0]),b=tryStartSuper(base.fighters[1],lockedInputs[1]);if(!commandA)a=startBounceLauncher(startAirJuggleLight(startHeavyLauncher(startLight(a,actionInputA),actionInputA),actionInputA),actionInputA);if(!commandB)b=startBounceLauncher(startAirJuggleLight(startHeavyLauncher(startLight(b,actionInputB),actionInputB),actionInputB),actionInputB);
 if(actionInputA.throw&&!throws[0]&&a.mode==="idle")throws[0]=beginThrow();if(actionInputB.throw&&!throws[1]&&b.mode==="idle")throws[1]=beginThrow();
 if(throws[0]){if(canTechThrow(throws[0],inputs[1].throw)){throws[0]=undefined;}else if(canThrowConnect(throws[0],a,b,BASIC_THROW,throws[1])){b={...b,health:Math.max(0,b.health-BASIC_THROW.damage),mode:"hitstun",stunFrames:BASIC_THROW.techWindow};throws[0]=undefined;}else throws[0]=advanceThrow(throws[0]);}
 if(throws[1]){if(canTechThrow(throws[1],inputs[0].throw)){throws[1]=undefined;}else if(canThrowConnect(throws[1],b,a,BASIC_THROW,throws[0])){a={...a,health:Math.max(0,a.health-BASIC_THROW.damage),mode:"hitstun",stunFrames:BASIC_THROW.techWindow};throws[1]=undefined;}else throws[1]=advanceThrow(throws[1]);}
 a=jumpCancelLauncher(a,actionInputA);b=jumpCancelLauncher(b,actionInputB);
 const superHpB=b.health;[a,b]=resolveBasicSuper(a,b,guards[1]);if(b.health<superHpB)combos=[addComboHit(combos[0],BASIC_SUPER.damage,frame).combo,combos[1]];const superHpA=a.health;[b,a]=resolveBasicSuper(b,a,guards[0]);if(a.health<superHpA)combos=[combos[0],addComboHit(combos[1],BASIC_SUPER.damage,frame).combo];
 const airHpB=b.health;if(canJuggle(juggles[0],1)){[a,b]=resolveAirJuggleLight(a,b);if(b.health<airHpB){juggles[0]=applyJuggle(juggles[0],1);combos=[addComboHit(combos[0],AIR_JUGGLE_LIGHT.damage,frame).combo,combos[1]];}}
 const airHpA=a.health;if(canJuggle(juggles[1],1)){[b,a]=resolveAirJuggleLight(b,a);if(a.health<airHpA){juggles[1]=applyJuggle(juggles[1],1);combos=[combos[0],addComboHit(combos[1],AIR_JUGGLE_LIGHT.damage,frame).combo];}}
 const bounceHpB=b.health;if(canJuggle(juggles[0],2)){[a,b]=resolveBounceLauncher(a,b,guards[1]);if(b.health<bounceHpB){juggles[0]=applyJuggle(juggles[0],2);combos=[addComboHit(combos[0],BOUNCE_LAUNCHER.damage,frame).combo,combos[1]];bounceEntitlements[1]={wall:!!BOUNCE_LAUNCHER.bounce?.wall,ground:!!BOUNCE_LAUNCHER.bounce?.ground};}}
 const bounceHpA=a.health;if(canJuggle(juggles[1],2)){[b,a]=resolveBounceLauncher(b,a,guards[0]);if(a.health<bounceHpA){juggles[1]=applyJuggle(juggles[1],2);combos=[combos[0],addComboHit(combos[1],BOUNCE_LAUNCHER.damage,frame).combo];bounceEntitlements[0]={wall:!!BOUNCE_LAUNCHER.bounce?.wall,ground:!!BOUNCE_LAUNCHER.bounce?.ground};}}
 const heavyHpB=b.health,heavyArmorB=hasArmor(defenseReactions[1]);if(canJuggle(juggles[0],2)){[a,b]=resolveHeavyLauncher(a,b,guards[1],armorDamage(defenseReactions[1],STANDING_HEAVY_LAUNCHER.damage));if(heavyArmorB&&a.attack?.contact==="hit"){defenseReactions[1]=absorbArmorHit(defenseReactions[1]);b={...combat.fighters[1],hitstopFrames:b.hitstopFrames};}else if(b.health<heavyHpB){juggles[0]=applyJuggle(juggles[0],2);combos=[addComboHit(combos[0],STANDING_HEAVY_LAUNCHER.damage,frame).combo,combos[1]];}}
 const heavyHpA=a.health,heavyArmorA=hasArmor(defenseReactions[0]);if(canJuggle(juggles[1],2)){[b,a]=resolveHeavyLauncher(b,a,guards[0],armorDamage(defenseReactions[0],STANDING_HEAVY_LAUNCHER.damage));if(heavyArmorA&&b.attack?.contact==="hit"){defenseReactions[0]=absorbArmorHit(defenseReactions[0]);a={...combat.fighters[0],hitstopFrames:a.hitstopFrames};}else if(a.health<heavyHpA){juggles[1]=applyJuggle(juggles[1],2);combos=[combos[0],addComboHit(combos[1],STANDING_HEAVY_LAUNCHER.damage,frame).combo];}}
 let bounces=[{...combat.bounces[0]},{...combat.bounces[1]}] as [typeof combat.bounces[0],typeof combat.bounces[1]];const ga=bounces[0].groundBounces,gb=bounces[1].groundBounces;if(bounceEntitlements[0].ground&&canJuggle(juggles[1],DEFAULT_BOUNCE_RULES.groundJuggleCost))[a,bounces[0]]=resolveGroundBounce(combat.fighters[0],a,bounces[0]);if(bounces[0].groundBounces>ga){juggles[1]=applyJuggle(juggles[1],DEFAULT_BOUNCE_RULES.groundJuggleCost);bounceEntitlements[0]={...bounceEntitlements[0],ground:false};}if(bounceEntitlements[1].ground&&canJuggle(juggles[0],DEFAULT_BOUNCE_RULES.groundJuggleCost))[b,bounces[1]]=resolveGroundBounce(combat.fighters[1],b,bounces[1]);if(bounces[1].groundBounces>gb){juggles[0]=applyJuggle(juggles[0],DEFAULT_BOUNCE_RULES.groundJuggleCost);bounceEntitlements[1]={...bounceEntitlements[1],ground:false};}const wa=bounces[0].wallBounces,wb=bounces[1].wallBounces;if(bounceEntitlements[0].wall&&canJuggle(juggles[1],DEFAULT_BOUNCE_RULES.wallJuggleCost))[a,bounces[0]]=resolveWallBounce(a,bounces[0]);if(bounces[0].wallBounces>wa){juggles[1]=applyJuggle(juggles[1],DEFAULT_BOUNCE_RULES.wallJuggleCost);bounceEntitlements[0]={...bounceEntitlements[0],wall:false};}if(bounceEntitlements[1].wall&&canJuggle(juggles[0],DEFAULT_BOUNCE_RULES.wallJuggleCost))[b,bounces[1]]=resolveWallBounce(b,bounces[1]);if(bounces[1].wallBounces>wb){juggles[0]=applyJuggle(juggles[0],DEFAULT_BOUNCE_RULES.wallJuggleCost);bounceEntitlements[1]={...bounceEntitlements[1],wall:false};}
 const juggleHpB=b.health;if(canJuggle(juggles[0],1)){[a,b]=resolveJuggleLight(a,b,scaledDamage(JUGGLE_LIGHT.damage,combos[0].hits));if(b.health<juggleHpB){juggles[0]=applyJuggle(juggles[0],1);combos=[addComboHit(combos[0],JUGGLE_LIGHT.damage,frame).combo,combos[1]];}}
 const juggleHpA=a.health;if(canJuggle(juggles[1],1)){[b,a]=resolveJuggleLight(b,a,scaledDamage(JUGGLE_LIGHT.damage,combos[1].hits));if(a.health<juggleHpA){juggles[1]=applyJuggle(juggles[1],1);combos=[combos[0],addComboHit(combos[1],JUGGLE_LIGHT.damage,frame).combo];}}
 const hpB=b.health,armorB=hasArmor(defenseReactions[1]),parryB=defenseReactions[1].kind==="parry",counterB=isCounterHitTarget(b.mode);[a,b]=resolveStandingLight(a,b,guards[1],armorDamage(defenseReactions[1],scaledDamage(STANDING_LIGHT.damage,combos[0].hits)));if(parryB&&a.attack?.contact==="hit"){defenseReactions[1]=resolveParry(defenseReactions[1]);a={...a,attack:a.attack?{...a.attack,contact:"parry"}:a.attack};b={...combat.fighters[1],hitstopFrames:b.hitstopFrames};}else if(armorB&&a.attack?.contact==="hit"){defenseReactions[1]=absorbArmorHit(defenseReactions[1]);b={...b,mode:"idle",stunFrames:0};}else if(b.health<hpB){if(counterB&&a.attack?.contact==="hit")a={...a,attack:{...a.attack,contact:"counter"}};a=gainMeter(a,LIGHT_HIT_METER_GAIN);combos=[addComboHit(combos[0],STANDING_LIGHT.damage,frame).combo,combos[1]];}
 const hpA=a.health,armorA=hasArmor(defenseReactions[0]),parryA=defenseReactions[0].kind==="parry",counterA=isCounterHitTarget(a.mode);[b,a]=resolveStandingLight(b,a,guards[0],armorDamage(defenseReactions[0],scaledDamage(STANDING_LIGHT.damage,combos[1].hits)));if(parryA&&b.attack?.contact==="hit"){defenseReactions[0]=resolveParry(defenseReactions[0]);b={...b,attack:b.attack?{...b.attack,contact:"parry"}:b.attack};a={...combat.fighters[0],hitstopFrames:a.hitstopFrames};}else if(armorA&&b.attack?.contact==="hit"){defenseReactions[0]=absorbArmorHit(defenseReactions[0]);a={...a,mode:"idle",stunFrames:0};}else if(a.health<hpA){if(counterA&&b.attack?.contact==="hit")b={...b,attack:{...b.attack,contact:"counter"}};b=gainMeter(b,LIGHT_HIT_METER_GAIN);combos=[combos[0],addComboHit(combos[1],STANDING_LIGHT.damage,frame).combo];}
 const preStunA=a.mode,preStunB=b.mode;if(!landedA&&a.hitstopFrames===0&&(a.mode==="hitstun"||a.mode==="air-hitstun"||a.mode==="knockdown"||a.mode==="blockstun"))a=tickStun(a);if(!landedB&&b.hitstopFrames===0&&(b.mode==="hitstun"||b.mode==="air-hitstun"||b.mode==="knockdown"||b.mode==="blockstun"))b=tickStun(b);const recoveredA=(preStunA==="hitstun"||preStunA==="knockdown")&&a.mode==="idle";const recoveredB=(preStunB==="hitstun"||preStunB==="knockdown")&&b.mode==="idle";if(recoveredA){juggles[1]={points:0,hits:0};bounces[0]={wallBounces:0,groundBounces:0};bounceEntitlements[0]={wall:false,ground:false};}if(recoveredB){juggles[0]={points:0,hits:0};bounces[1]={wallBounces:0,groundBounces:0};bounceEntitlements[1]={wall:false,ground:false};}
 a=advanceAttack(a);b=advanceAttack(b);defenseReactions=[tickDefenseReaction(defenseReactions[0]),tickDefenseReaction(defenseReactions[1])];
 const projectileContact=resolveProjectileContacts(tickProjectiles(projectiles),[a,b]);[a,b]=projectileContact.fighters;
 return{...base,fighters:[a,b] as readonly[FighterState,FighterState],combos,throws,juggles,bounces,bounceEntitlements,defenseReactions,projectiles:projectileContact.projectiles,nextProjectileId,projectileCommandHeld:projectileCommands};
}
