import type{FighterState,PlayerId}from"@forged-fighter/core";import{applyHit}from"@forged-fighter/core";import{intersects,STANDING_BODY_HURTBOX,toWorldBox}from"./boxes.js";
export interface ProjectileState{id:number;owner:PlayerId;x:number;y:number;vx:number;vy:number;lifetime:number;damage:number;hitstun:number;hitstop:number;width:number;height:number;}
export interface ProjectileSpawn{owner:PlayerId;x:number;y:number;vx:number;vy?:number;lifetime:number;damage:number;hitstun:number;hitstop:number;width:number;height:number;}
export function spawnProjectile(nextId:number,spawn:ProjectileSpawn):readonly[ProjectileState,number]{return[{id:nextId,owner:spawn.owner,x:spawn.x,y:spawn.y,vx:spawn.vx,vy:spawn.vy??0,lifetime:Math.max(0,spawn.lifetime),damage:Math.max(0,spawn.damage),hitstun:Math.max(0,spawn.hitstun),hitstop:Math.max(0,spawn.hitstop),width:Math.max(0,spawn.width),height:Math.max(0,spawn.height)},nextId+1];}
export function tickProjectile(p:ProjectileState):ProjectileState|undefined{return p.lifetime<=1?undefined:{...p,x:p.x+p.vx,y:p.y+p.vy,lifetime:p.lifetime-1};}
export function tickProjectiles(projectiles:readonly ProjectileState[]):readonly ProjectileState[]{return projectiles.map(tickProjectile).filter((p):p is ProjectileState=>p!==undefined);}
export interface ProjectileContactResult{projectiles:readonly ProjectileState[];fighters:readonly[FighterState,FighterState];}
export function resolveProjectileContacts(projectiles:readonly ProjectileState[],fighters:readonly[FighterState,FighterState]):ProjectileContactResult{let next:[FighterState,FighterState]=[{...fighters[0]},{...fighters[1]}];const remaining:ProjectileState[]=[];for(const p of projectiles){const target=p.owner===0?1:0;const defender=next[target];const hit={owner:p.owner,x:p.x-p.width/2,y:p.y-p.height/2,width:p.width,height:p.height}as const;const hurt=toWorldBox(STANDING_BODY_HURTBOX,defender.playerId,defender.x,defender.y,defender.facing);if(intersects(hit,hurt)){next[target]=applyHit(defender,p.damage,p.hitstun,p.hitstop);}else remaining.push(p);}return{projectiles:remaining,fighters:next};}
export function spawnBasicProjectile(nextId:number,fighter:FighterState):readonly[ProjectileState,number]{return spawnProjectile(nextId,{owner:fighter.playerId,x:fighter.x+fighter.facing*48,y:fighter.y+48,vx:fighter.facing*12,lifetime:90,damage:400,hitstun:8,hitstop:4,width:24,height:24});}
