import type { FighterInput,FighterState } from "@forged-fighter/core";
import { applyBlock,applyHit,applyHitstop,beginAttack } from "@forged-fighter/core";
import { attackPhase } from "./frame-data.js";import { detectHit } from "./hit-detection.js";import { toWorldBox } from "./boxes.js";import { AIR_JUGGLE_LIGHT,BOUNCE_LAUNCHER,JUGGLE_LIGHT,STANDING_HEAVY_LAUNCHER,STANDING_LIGHT } from "./moves.js";import{launchFighter,type LaunchData}from"./air-combat.js";
function launchData(move:{hitstun:number;landingKnockdownFrames?:number},velocityX:number,velocityY:number,juggleCost:number):LaunchData{const base={velocityX,velocityY,airHitstun:move.hitstun,juggleCost};return move.landingKnockdownFrames===undefined?base:{...base,landingKnockdownFrames:move.landingKnockdownFrames};}
export function startAirJuggleLight(f:FighterState,input:FighterInput):FighterState{return input.light&&!f.grounded&&(f.mode==="jump"||f.mode==="fall"||f.mode==="idle")?beginAttack(f,AIR_JUGGLE_LIGHT.id):f;}
export function startBounceLauncher(f:FighterState,input:FighterInput):FighterState{return input.special&&f.mode==="idle"?beginAttack(f,BOUNCE_LAUNCHER.id):f;}
export function startJuggleLight(f:FighterState,input:FighterInput,opponent:FighterState):FighterState{return input.light&&f.mode==="idle"&&opponent.mode==="air-hitstun"?beginAttack(f,JUGGLE_LIGHT.id):f;}
export function startHeavyLauncher(f:FighterState,input:FighterInput):FighterState{return input.heavy&&f.mode==="idle"?beginAttack(f,STANDING_HEAVY_LAUNCHER.id):f;}
export function startLight(f:FighterState,input:FighterInput):FighterState{return input.light&&f.mode==="idle"?beginAttack(f,STANDING_LIGHT.id):f;}
export function isBlocking(defender:FighterState,input:FighterInput):boolean{return defender.grounded&&(defender.facing===1?input.left:input.right);}
export function resolveStandingLight(attacker:FighterState,defender:FighterState,defenderInput?:FighterInput,damage=STANDING_LIGHT.damage):readonly[FighterState,FighterState]{
 const a=attacker.attack;if(!a||a.moveId!==STANDING_LIGHT.id||attackPhase(STANDING_LIGHT,a.frame)!=="active"||a.hasHit)return[attacker,defender];
 const hit=toWorldBox(STANDING_LIGHT.hitbox,attacker.playerId,attacker.x,attacker.y,attacker.facing),hurt=toWorldBox(STANDING_LIGHT.hurtbox,defender.playerId,defender.x,defender.y,defender.facing);
 if(!detectHit(hit,[hurt]))return[attacker,defender];
 const connected={...attacker,attack:{...a,hasHit:true}};
 const stopped=applyHitstop(connected,STANDING_LIGHT.hitstop);
 return isBlocking(defender,defenderInput??({} as FighterInput))?[stopped,applyBlock(defender,STANDING_LIGHT.blockstun,STANDING_LIGHT.hitstop)]:[stopped,applyHit(defender,damage,STANDING_LIGHT.hitstun,STANDING_LIGHT.hitstop)];
}
export function resolveAirJuggleLight(attacker:FighterState,defender:FighterState):readonly[FighterState,FighterState]{const a=attacker.attack;if(!a||a.moveId!==AIR_JUGGLE_LIGHT.id||attackPhase(AIR_JUGGLE_LIGHT,a.frame)!=="active"||a.hasHit||defender.mode!=="air-hitstun")return[attacker,defender];const hit=toWorldBox(AIR_JUGGLE_LIGHT.hitbox,attacker.playerId,attacker.x,attacker.y,attacker.facing),hurt=toWorldBox(AIR_JUGGLE_LIGHT.hurtbox,defender.playerId,defender.x,defender.y,defender.facing);if(!detectHit(hit,[hurt]))return[attacker,defender];const connected=applyHitstop({...attacker,attack:{...a,hasHit:true}},AIR_JUGGLE_LIGHT.hitstop);const damaged={...defender,health:Math.max(0,defender.health-AIR_JUGGLE_LIGHT.damage),hitstopFrames:AIR_JUGGLE_LIGHT.hitstop};return[connected,launchFighter(damaged,launchData(AIR_JUGGLE_LIGHT,attacker.facing*5,18,1))];}
export function resolveBounceLauncher(attacker:FighterState,defender:FighterState,defenderInput?:FighterInput):readonly[FighterState,FighterState]{const a=attacker.attack;if(!a||a.moveId!==BOUNCE_LAUNCHER.id||attackPhase(BOUNCE_LAUNCHER,a.frame)!=="active"||a.hasHit)return[attacker,defender];const hit=toWorldBox(BOUNCE_LAUNCHER.hitbox,attacker.playerId,attacker.x,attacker.y,attacker.facing),hurt=toWorldBox(BOUNCE_LAUNCHER.hurtbox,defender.playerId,defender.x,defender.y,defender.facing);if(!detectHit(hit,[hurt]))return[attacker,defender];const connected=applyHitstop({...attacker,attack:{...a,hasHit:true}},BOUNCE_LAUNCHER.hitstop);if(isBlocking(defender,defenderInput??({} as FighterInput)))return[connected,applyBlock(defender,BOUNCE_LAUNCHER.blockstun,BOUNCE_LAUNCHER.hitstop)];const damaged={...defender,health:Math.max(0,defender.health-BOUNCE_LAUNCHER.damage),hitstopFrames:BOUNCE_LAUNCHER.hitstop};return[connected,launchFighter(damaged,launchData(BOUNCE_LAUNCHER,attacker.facing*10,30,2))];}
export function resolveJuggleLight(attacker:FighterState,defender:FighterState,damage=JUGGLE_LIGHT.damage):readonly[FighterState,FighterState]{const a=attacker.attack;if(!a||a.moveId!==JUGGLE_LIGHT.id||attackPhase(JUGGLE_LIGHT,a.frame)!=="active"||a.hasHit||defender.mode!=="air-hitstun")return[attacker,defender];const hit=toWorldBox(JUGGLE_LIGHT.hitbox,attacker.playerId,attacker.x,attacker.y,attacker.facing),hurt=toWorldBox(JUGGLE_LIGHT.hurtbox,defender.playerId,defender.x,defender.y,defender.facing);if(!detectHit(hit,[hurt]))return[attacker,defender];return[applyHitstop({...attacker,attack:{...a,hasHit:true}},JUGGLE_LIGHT.hitstop),launchFighter({...defender,health:Math.max(0,defender.health-damage),hitstopFrames:JUGGLE_LIGHT.hitstop},{velocityX:attacker.facing*5,velocityY:18,airHitstun:JUGGLE_LIGHT.hitstun,juggleCost:1})];}
export function resolveHeavyLauncher(attacker:FighterState,defender:FighterState,defenderInput?:FighterInput):readonly[FighterState,FighterState]{const a=attacker.attack;if(!a||a.moveId!==STANDING_HEAVY_LAUNCHER.id||attackPhase(STANDING_HEAVY_LAUNCHER,a.frame)!=="active"||a.hasHit)return[attacker,defender];const hit=toWorldBox(STANDING_HEAVY_LAUNCHER.hitbox,attacker.playerId,attacker.x,attacker.y,attacker.facing),hurt=toWorldBox(STANDING_HEAVY_LAUNCHER.hurtbox,defender.playerId,defender.x,defender.y,defender.facing);if(!detectHit(hit,[hurt]))return[attacker,defender];const connected=applyHitstop({...attacker,attack:{...a,hasHit:true}},STANDING_HEAVY_LAUNCHER.hitstop);if(isBlocking(defender,defenderInput??({} as FighterInput)))return[connected,applyBlock(defender,STANDING_HEAVY_LAUNCHER.blockstun,STANDING_HEAVY_LAUNCHER.hitstop)];const damaged={...defender,health:Math.max(0,defender.health-STANDING_HEAVY_LAUNCHER.damage),hitstopFrames:STANDING_HEAVY_LAUNCHER.hitstop};return[connected,launchFighter(damaged,launchData(STANDING_HEAVY_LAUNCHER,attacker.facing*8,28,2))];}
export function advanceAttack(f:FighterState):FighterState{const a=f.attack;if(!a||f.hitstopFrames>0)return f;const next=a.frame+1;const move=a.moveId===BOUNCE_LAUNCHER.id?BOUNCE_LAUNCHER:a.moveId===STANDING_HEAVY_LAUNCHER.id?STANDING_HEAVY_LAUNCHER:a.moveId===AIR_JUGGLE_LIGHT.id?AIR_JUGGLE_LIGHT:STANDING_LIGHT;if(attackPhase(move,next)==="complete"){const{attack:_attack,...rest}=f;return{...rest,mode:f.grounded?"idle":"fall"};}return{...f,attack:{...a,frame:next}};}
