import{describe,expect,it}from"vitest";import{beginAttack,createInitialState,type FighterInput,FighterState}from"@forged-fighter/core";import{advanceAttack}from"./runtime.js";import{STANDING_LIGHT}from"./moves.js";import{EMPTY_COMBO}from"./combo.js";import{beginArmor,beginParry,EMPTY_DEFENSE_REACTION}from"./defense-reactions.js";import{LIGHT_HIT_METER_GAIN}from"./meter.js";import{resolveStandingLightContact}from"./standing-light-resolution.js";
const n=():FighterInput=>({left:false,right:false,up:false,down:false,light:false,medium:false,heavy:false,special:false,throw:false});const active=()=>{let a={...createInitialState().fighters[0],x:0};a=beginAttack(a,STANDING_LIGHT.id);for(let i=0;i<STANDING_LIGHT.startup;i++)a=advanceAttack(a);return a;};const defender=(mode:FighterState["mode"]="idle"):FighterState=>({...createInitialState().fighters[1],x:60,mode});
describe("standing light resolution",()=>{
 it("records normal hit, combo and meter once",()=>{const a=active(),d=defender(),r=resolveStandingLightContact(a,d,d,n(),EMPTY_COMBO,EMPTY_DEFENSE_REACTION,30);expect(r.result).toBe("hit");expect(r.combo.hits).toBe(1);expect(r.attacker.meter-a.meter).toBe(LIGHT_HIT_METER_GAIN);});
 it("marks counter hit and still records one combo/meter gain",()=>{const a=active(),d=defender("attack"),r=resolveStandingLightContact(a,d,d,n(),EMPTY_COMBO,EMPTY_DEFENSE_REACTION,30);expect(r.result).toBe("counter");expect(r.attacker.attack?.contact).toBe("counter");expect(r.combo.hits).toBe(1);expect(r.attacker.meter-a.meter).toBe(LIGHT_HIT_METER_GAIN);});
 it("armor absorbs without combo or meter",()=>{const a=active(),d=defender(),r=resolveStandingLightContact(a,d,d,n(),EMPTY_COMBO,beginArmor(10),30);expect(r.result).toBe("armor");expect(r.combo).toEqual(EMPTY_COMBO);expect(r.attacker.meter).toBe(a.meter);expect(r.defender.mode).toBe("idle");expect(r.defenseReaction.lastResult).toBe("armor");});
 it("parry takes precedence and restores defender snapshot without combo or meter",()=>{const a=active(),d=defender(),snap={...d,vx:7},r=resolveStandingLightContact(a,d,snap,n(),EMPTY_COMBO,beginParry(10),30);expect(r.result).toBe("parry");expect(r.attacker.attack?.contact).toBe("parry");expect(r.combo).toEqual(EMPTY_COMBO);expect(r.attacker.meter).toBe(a.meter);expect(r.defender.vx).toBe(7);expect(r.defenseReaction.lastResult).toBe("parry");});
 it("returns none on miss",()=>{const a=active(),d={...defender(),x:500},r=resolveStandingLightContact(a,d,d,n(),EMPTY_COMBO,EMPTY_DEFENSE_REACTION,30);expect(r.result).toBe("none");expect(r.combo).toEqual(EMPTY_COMBO);expect(r.attacker.meter).toBe(a.meter);});
});
