import type{FighterInput,Ruleset}from"@forged-fighter/core";import{TraditionalRuleset,type TraditionalInput}from"./traditional-ruleset.js";import type{CombatMatchState}from"./combat-match.js";import{addComboHit,scaledDamage}from"./combo.js";
export interface TagInput{fighters:TraditionalInput;tag:readonly[boolean,boolean];assist:readonly[boolean,boolean];}
export interface AssistState{activeFrames:number;cooldown:number;hasHit:boolean;}
export interface TagTeamState{active:0|1;roster:readonly[number,number];tagCooldown:number;reserveHealth:readonly[number,number];assist:AssistState;}
export interface TagMatchState extends CombatMatchState{teams:readonly[TagTeamState,TagTeamState];}
export const TAG_COOLDOWN=180,ASSIST_COOLDOWN=240,ASSIST_ACTIVE_FRAMES=24,ASSIST_HIT_FRAME=8,ASSIST_RANGE=150,ASSIST_DAMAGE=350,ASSIST_HITSTUN=12,RESERVE_RECOVERY_PER_FRAME=2;
function initialTeam():TagTeamState{return{active:0,roster:[0,1],tagCooldown:0,reserveHealth:[10000,10000],assist:{activeFrames:0,cooldown:0,hasHit:false}};}
export const TagRuleset:Ruleset<TagMatchState,TagInput>={metadata:{id:"forged.tag",version:"1.2.0",displayName:"Tag Fighter",capabilities:["teams","tag","assists","air-dash","wall-bounce","ground-bounce"]},createInitialState(seed){return{...TraditionalRuleset.createInitialState(seed),teams:[initialTeam(),initialTeam()]};},step(state,input){const base=TraditionalRuleset.step(state,input.fighters);const teams=state.teams.map((team,index)=>{const p=index as 0|1,tagCooldown=Math.max(0,team.tagCooldown-1);let active=team.active;const reserve=active===0?1:0;const health=[...team.reserveHealth] as[number,number];health[active]=base.fighters[p].health;health[reserve]=Math.min(10000,health[reserve]+RESERVE_RECOVERY_PER_FRAME);let assist={...team.assist,activeFrames:Math.max(0,team.assist.activeFrames-1),cooldown:Math.max(0,team.assist.cooldown-1)};if(input.assist[p]&&assist.cooldown===0)assist={activeFrames:ASSIST_ACTIVE_FRAMES,cooldown:ASSIST_COOLDOWN,hasHit:false};if(input.tag[p]&&tagCooldown===0)active=active===0?1:0;return{...team,active,tagCooldown:input.tag[p]&&tagCooldown===0?TAG_COOLDOWN:tagCooldown,reserveHealth:health,assist};}) as unknown as readonly[TagTeamState,TagTeamState];let fighters=[base.fighters[0],base.fighters[1]] as typeof base.fighters;let combos=[base.combos[0],base.combos[1]] as typeof base.combos;const mutableTeams=[teams[0],teams[1]] as[TagTeamState,TagTeamState];for(const p of[0,1]as const){const opponent=(1-p)as 0|1,assist=mutableTeams[p].assist;if(assist.activeFrames===ASSIST_ACTIVE_FRAMES-ASSIST_HIT_FRAME&&!assist.hasHit&&Math.abs(fighters[p].x-fighters[opponent].x)<=ASSIST_RANGE){const hit=addComboHit(combos[p],ASSIST_DAMAGE,base.frame);const damage=scaledDamage(ASSIST_DAMAGE,combos[p].hits);fighters=[...fighters] as typeof fighters;fighters[opponent]={...fighters[opponent],health:Math.max(0,fighters[opponent].health-damage),mode:"hitstun",stunFrames:ASSIST_HITSTUN};combos=[...combos] as typeof combos;combos[p]=hit.combo;mutableTeams[p]={...mutableTeams[p],assist:{...assist,hasHit:true}};}}return{...base,fighters,combos,teams:mutableTeams};},validate(state){const errors=[...TraditionalRuleset.validate(state)];for(const[index,team]of state.teams.entries()){if(team.active!==0&&team.active!==1)errors.push(`invalid active fighter for team ${index}`);if(team.tagCooldown<0||!Number.isInteger(team.tagCooldown))errors.push(`invalid tag cooldown for team ${index}`);if(team.assist.activeFrames<0||team.assist.cooldown<0)errors.push(`invalid assist state for team ${index}`);for(const hp of team.reserveHealth)if(!Number.isInteger(hp)||hp<0||hp>10000)errors.push(`invalid roster health for team ${index}`);}return errors;}};
export function neutralTagInput(neutral:()=>FighterInput):TagInput{return{fighters:[neutral(),neutral()],tag:[false,false],assist:[false,false]};}
